import { useNavigate, useLocation } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import ArgusLogo from '../components/ArgusLogo';
import { CodeBlock, Mono, ExternalA } from '../components/SetupPage/SetupPage';
import type { SetupStep } from '../components/SetupPage/SetupPage';
import teamsUrl from '../images/microsoft-teams.svg?url';
import slackUrl from '../images/slack.svg?url';

// --- Teams content ---

const TUNNEL_SETUP = `devtunnel create argus-tunnel --allow-anonymous
devtunnel port create argus-tunnel -p 7411`;

const BOT_CREATE = `teams login
teams app create --name "Argus" \\
  --endpoint "https://<endpoint>/api/v1/teams/webhook" \\
  --env .env`;

const TEAMS_STEPS: SetupStep[] = [
  {
    title: 'Set up a tunnel',
    body: (
      <>
        <p className="text-sm text-gray-600 mb-3">Teams delivers webhook events to Argus over HTTPS. Since Argus runs on your local machine, use a dev tunnel to expose it.</p>
        <p className="text-sm text-gray-600 mb-1">Create a persistent tunnel (one-time):</p>
        <div className="flex items-center gap-3 mt-2 mb-2">
          <Mono>devtunnel login</Mono>
          <span className="text-xs text-gray-400">Sign in with your GitHub or personal Microsoft account.</span>
        </div>
        <CodeBlock value={TUNNEL_SETUP} />
        <p className="text-sm text-gray-600 mt-3 mb-1">Start it each session:</p>
        <CodeBlock value="devtunnel host argus-tunnel" />
        <p className="text-sm text-gray-600 mt-3">Note the printed URL, e.g. <Mono>{'https://<tunnel-id>-7411.<region>.devtunnels.ms'}</Mono>. This is your <Mono>{'<endpoint>'}</Mono> in the next step.</p>
      </>
    ),
  },
  {
    title: 'Create the bot',
    body: (
      <>
        <CodeBlock value={BOT_CREATE} />
        <p className="text-sm text-gray-600 mt-3">This registers the bot, generates credentials (<strong>Client ID</strong>, <strong>Client Secret</strong>, <strong>Tenant ID</strong>), and prints an install link. Open the install link to add the bot to your team.</p>
        <p className="text-xs text-gray-400 mt-2">Use your tunnel URL for <Mono>{'<endpoint>'}</Mono> during local dev, or your server's public domain in production.</p>
      </>
    ),
  },
  {
    title: 'Get your Team ID, Channel ID, and AAD Object ID',
    body: (
      <ol className="space-y-3 text-sm text-gray-600 list-decimal pl-4">
        <li><strong>Team ID:</strong> Right-click the team name in Teams &rarr; <strong>Get link to team</strong>. The <Mono>groupId</Mono> parameter is your <strong>Team ID</strong>.</li>
        <li><strong>Channel ID:</strong> Right-click the channel &rarr; <strong>Get link to channel</strong>. The decoded value starting with <Mono>19:</Mono> is your <strong>Channel ID</strong> (format: <Mono>{'19:xxxxxxxx@thread.tacv2'}</Mono>).</li>
        <li><strong>AAD Object ID:</strong> In the <ExternalA href="https://portal.azure.com">Azure portal</ExternalA>, go to <strong>Microsoft Entra ID &rarr; Users</strong>, click your account, and copy the <strong>Object ID</strong>. This is your <strong>Owner AAD Object ID</strong>.</li>
      </ol>
    ),
  },
  {
    title: 'Configure Argus',
    body: (
      <>
        <p className="text-sm text-gray-600 mb-2">Open the Argus Settings dialog and go to the <strong>Microsoft Teams</strong> section. Enter the values from the previous steps:</p>
        <ul className="space-y-1 text-sm text-gray-600 list-disc pl-4 mb-3">
          <li><strong>Team ID</strong> and <strong>Channel ID</strong> from your Teams workspace</li>
          <li><strong>Owner AAD Object ID</strong> (your Azure AD user object ID)</li>
          <li><strong>Client ID</strong>, <strong>Client Secret</strong>, and <strong>Tenant ID</strong> generated by the bot create command</li>
        </ul>
        <p className="text-sm text-gray-600">Click <strong>Save</strong>, then restart Argus.</p>
      </>
    ),
  },
  {
    title: 'Verify the connection',
    body: (
      <>
        <p className="text-sm text-gray-600 mb-1">Check the server logs on startup for:</p>
        <CodeBlock value="teams: configured, subscribing to session events" />
        <p className="text-sm text-gray-600 mt-3 mb-1">Mention the bot in the channel to confirm it is reachable:</p>
        <CodeBlock value="@Argus help" />
      </>
    ),
  },
];

const TEAMS_PREREQUISITES = (
  <ul className="space-y-1.5 text-sm text-gray-600 list-disc pl-4">
    <li><ExternalA href="https://microsoft.github.io/teams-sdk/">Teams CLI</ExternalA> installed: <Mono>npm install -g @microsoft/teams.cli@preview</Mono></li>
    <li>A Microsoft Teams workspace where you are a team owner or admin. Get <ExternalA href="https://www.microsoft.com/en-us/microsoft-teams/essentials">Teams Essentials</ExternalA> or an <ExternalA href="https://www.microsoft.com/en-us/microsoft-365/business/microsoft-365-plans-and-pricing">M365 tenant</ExternalA> if you don't have one.</li>
    <li>For local dev: <ExternalA href="https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/">Azure Dev Tunnels CLI</ExternalA> — <Mono>winget install Microsoft.DevTunnel</Mono> or <Mono>brew install devtunnel</Mono>.</li>
  </ul>
);

// --- Slack content ---

const SCOPES = [
  ['chat:write',        'Post messages and thread replies'],
  ['channels:read',     'Look up channel information'],
  ['app_mentions:read', 'Receive @mention events'],
  ['im:history',        'Receive direct messages'],
] as const;

const LOG_BLOCK = `[SlackNotifier] Initialized, posting to channel C01234ABCDE
[SlackListener] Socket Mode connected, listening for app mentions and DMs`;

const SLACK_STEPS: SetupStep[] = [
  {
    title: 'Create the app',
    body: (
      <ol className="space-y-1.5 text-sm text-gray-600 list-decimal pl-4">
        <li>Go to <ExternalA href="https://api.slack.com/apps">api.slack.com/apps</ExternalA> and sign in.</li>
        <li>Click <strong>Create New App</strong> &rarr; <strong>From scratch</strong>.</li>
        <li>Name the app (e.g. <Mono>Argus</Mono>) and select your workspace.</li>
        <li>Click <strong>Create App</strong>.</li>
      </ol>
    ),
  },
  {
    title: 'Add bot token scopes',
    body: (
      <>
        <ol className="space-y-1.5 text-sm text-gray-600 list-decimal pl-4 mb-3">
          <li>In the left sidebar, click <strong>OAuth and Permissions</strong>.</li>
          <li>Scroll to <strong>Scopes &rarr; Bot Token Scopes</strong> and add these four:</li>
        </ol>
        <table className="w-full text-xs border-collapse">
          <thead>
            <tr className="border-b border-gray-200">
              <th className="text-left font-medium text-gray-500 py-1.5 pr-6 w-2/5">Scope</th>
              <th className="text-left font-medium text-gray-500 py-1.5">Purpose</th>
            </tr>
          </thead>
          <tbody>
            {SCOPES.map(([scope, purpose]) => (
              <tr key={scope} className="border-b border-gray-100">
                <td className="py-1.5 pr-6 font-mono text-gray-800">{scope}</td>
                <td className="py-1.5 text-gray-600">{purpose}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </>
    ),
  },
  {
    title: 'Enable Socket Mode',
    body: (
      <>
        <ol className="space-y-1.5 text-sm text-gray-600 list-decimal pl-4 mb-3">
          <li>Click <strong>Socket Mode</strong> in the sidebar and toggle it on.</li>
          <li>When prompted, create an App-level token: name it anything (e.g. <Mono>argus-socket</Mono>), add scope <Mono>connections:write</Mono>, click <strong>Generate</strong>.</li>
          <li>Copy the <Mono>xapp-...</Mono> token — this is your <strong>App Token</strong>.</li>
        </ol>
        <p className="text-xs text-gray-400">Skip this step if you only need outbound notifications and don't need the bot to respond to commands.</p>
      </>
    ),
  },
  {
    title: 'Subscribe to bot events',
    body: (
      <ol className="space-y-1.5 text-sm text-gray-600 list-decimal pl-4">
        <li>Click <strong>Event Subscriptions</strong> in the sidebar and toggle <strong>Enable Events</strong> on.</li>
        <li>Under <strong>Subscribe to bot events</strong>, add <Mono>app_mention</Mono> and <Mono>message.im</Mono>.</li>
        <li>Click <strong>Save Changes</strong>.</li>
      </ol>
    ),
  },
  {
    title: 'Install to your workspace',
    body: (
      <ol className="space-y-1.5 text-sm text-gray-600 list-decimal pl-4">
        <li>Click <strong>OAuth and Permissions</strong> in the sidebar.</li>
        <li>Click <strong>Install to Workspace</strong> and allow the permissions.</li>
        <li>Copy the <strong>Bot User OAuth Token</strong> (<Mono>xoxb-...</Mono>) — this is your <strong>Bot Token</strong>.</li>
      </ol>
    ),
  },
  {
    title: 'Get your channel ID',
    body: (
      <>
        <ol className="space-y-1.5 text-sm text-gray-600 list-decimal pl-4 mb-2">
          <li>In Slack, open the channel you want Argus to post to.</li>
          <li>Right-click the channel name &rarr; <strong>View channel details</strong>.</li>
          <li>Scroll to the bottom and copy the Channel ID (format: <Mono>C01234ABCDE</Mono>) — this is your <strong>Channel ID</strong>.</li>
          <li>Invite the bot to the channel:</li>
        </ol>
        <CodeBlock value="/invite @Argus" />
      </>
    ),
  },
  {
    title: 'Configure Argus',
    body: (
      <>
        <p className="text-sm text-gray-600 mb-2">Open the Argus Settings dialog and go to the <strong>Slack</strong> section. Enter the values from the previous steps:</p>
        <ul className="space-y-1 text-sm text-gray-600 list-disc pl-4 mb-3">
          <li><strong>Bot Token</strong> (<Mono>xoxb-...</Mono>) from the OAuth &amp; Permissions page</li>
          <li><strong>Channel ID</strong> of the channel where Argus will post</li>
          <li><strong>App Token</strong> (<Mono>xapp-...</Mono>) if you want inbound commands via Socket Mode</li>
        </ul>
        <p className="text-sm text-gray-600">Click <strong>Save</strong>.</p>
      </>
    ),
  },
  {
    title: 'Verify the connection',
    body: (
      <>
        <p className="text-sm text-gray-600 mb-1">Restart Argus and check the server logs for:</p>
        <CodeBlock value={LOG_BLOCK} />
        <p className="text-sm text-gray-600 mt-3 mb-1">Type this in your Slack channel to confirm the bot responds:</p>
        <CodeBlock value="@Argus help" />
      </>
    ),
  },
];

const SLACK_PREREQUISITES = (
  <ul className="space-y-1.5 text-sm text-gray-600 list-disc pl-4">
    <li>A Slack workspace — free tier is sufficient. <ExternalA href="https://slack.com/help/articles/206845317-Create-a-Slack-workspace">Create one</ExternalA> if you don't have one.</li>
    <li>Admin access to the workspace, or permission to install apps.</li>
  </ul>
);

// --- Tab config ---

type TabId = 'teams' | 'slack';

const TABS: { id: TabId; label: string; path: string; logoSrc: string; steps: SetupStep[]; prerequisites: React.ReactNode }[] = [
  { id: 'teams', label: 'Microsoft Teams', path: '/setup/teams', logoSrc: teamsUrl, steps: TEAMS_STEPS, prerequisites: TEAMS_PREREQUISITES },
  { id: 'slack', label: 'Slack',           path: '/setup/slack', logoSrc: slackUrl, steps: SLACK_STEPS, prerequisites: SLACK_PREREQUISITES },
];

// --- Stepper ---

function StepList({ steps }: { steps: SetupStep[] }) {
  return (
    <div className="bg-white border border-gray-200 rounded-lg px-6 py-5">
      {steps.map((step, i) => (
        <div key={step.title} className="flex gap-4">
          <div className="flex flex-col items-center">
            <div className="flex items-center justify-center w-6 h-6 rounded-full bg-blue-600 text-white text-xs font-semibold shrink-0">
              {i + 1}
            </div>
            {i < steps.length - 1 && <div className="w-px flex-1 bg-gray-100 my-1.5" />}
          </div>
          <div className={`flex-1 ${i < steps.length - 1 ? 'pb-6' : 'pb-0'}`}>
            <h2 className="text-sm font-semibold text-gray-900 mb-2 leading-6">{step.title}</h2>
            {step.body}
          </div>
        </div>
      ))}
    </div>
  );
}

// --- Page ---

export default function IntegrationsSetupPage() {
  const navigate = useNavigate();
  const location = useLocation();

  const activeTab = TABS.find(t => t.path === location.pathname) ?? TABS[0];

  return (
    <div className="min-h-screen bg-slate-50 p-6 md:p-12">
      <div className="mx-auto max-w-5xl">

        <div className="mb-8">
          <button onClick={() => navigate('/')} className="icon-btn text-sm text-gray-600 hover:text-blue-600 mb-6 flex items-center gap-1.5">
            <ArrowLeft size={14} aria-hidden="true" /> Back
          </button>
          <div className="flex items-center gap-2.5 mb-1">
            <ArgusLogo size={24} />
            <h1 className="text-xl font-semibold text-gray-900">Integration Setup</h1>
          </div>
          <p className="text-sm text-gray-500">Connect Argus to Microsoft Teams or Slack.</p>
        </div>

        {/* Tabs */}
        <div className="flex gap-1 mb-6 border-b border-gray-200">
          {TABS.map(tab => (
            <button
              key={tab.id}
              type="button"
              onClick={() => navigate(tab.path)}
              className={`flex items-center gap-2 px-4 py-2.5 text-sm font-medium border-b-2 -mb-px transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-blue-400 ${
                tab.id === activeTab.id
                  ? 'border-blue-600 text-blue-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              <img src={tab.logoSrc} alt="" width={16} height={16} aria-hidden="true" />
              {tab.label}
            </button>
          ))}
        </div>

        {/* Prerequisites */}
        <div className="bg-white border border-gray-200 rounded-lg px-6 py-5 mb-4">
          <h2 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">Prerequisites</h2>
          {activeTab.prerequisites}
        </div>

        {/* Steps */}
        <StepList steps={activeTab.steps} />

        <div className="mt-6">
          <button onClick={() => navigate('/')} className="icon-btn text-sm text-gray-500 hover:text-blue-600 flex items-center gap-1.5">
            <ArrowLeft size={13} aria-hidden="true" /> Back to Argus
          </button>
        </div>

      </div>
    </div>
  );
}
